// Writes the Flack version (root package.json) into the functions source, which deploys
// without the root package.json. Run by the functions build; a unit test checks it's current.
import { readFileSync, writeFileSync } from 'node:fs';

const { version } = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));
const file = new URL('../firebase/functions/src/version.ts', import.meta.url);
const next = `// Generated by scripts/stamp-version.mjs from the root package.json. Don't edit.\nexport const FLACK_VERSION = '${version}';\n`;
let current = '';
try {
  current = readFileSync(file, 'utf8');
} catch {
  // first run
}
if (current !== next) writeFileSync(file, next);
